a.out: main.cpp blueDiamond.cpp door.cpp item.cpp levelinfo.cpp message.cpp puddle.cpp redPuddle.cpp settings.cpp blueDoor.cpp greenPuddle.cpp levelBar.cpp player.cpp redDiamond.cpp reversetile.cpp tile.cpp bluePuddle.cpp input.cpp level.cpp melody.cpp playerinfo.cpp redDoor.cpp score.cpp widget.cpp

	g++ -g -O0 $^

.PHONY: clean
clean:
	rm a.out
